name: Build Editor Windows

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build-editor-win:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0
      
    - name: Conan setup and install dependencies
      working-directory: ${{github.workspace}}/editor
      run: |
        conan profile detect --force
        conan config install ../conan_config
        conan remote add artifactory http://artifactory.matthewcotton.net/artifactory/api/conan/conan-local
        conan remote login artifactory ci -p ${{ secrets.ARTIFACTS_TOKEN }}
        conan install . --build=missing --profile windows_profile
        conan install . --build=missing --profile windows_profile -s build_type=Debug
        conan upload "*" -r=artifactory -c
        ./build/generators/conanbuild.bat

    - name: Configure CMake
      working-directory: ${{github.workspace}}/editor
      run: cmake --preset conan-default

    - name: Build Release
      working-directory: ${{github.workspace}}/editor
      run: cmake --build --preset conan-release -j

    - name: Build Debug
      working-directory: ${{github.workspace}}/editor
      run: cmake --build --preset conan-debug -j
