name: Upload Library

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-and-upload:
    if: github.repository == 'instinkt900/moth_ui'
    runs-on: ${{ matrix.os == 'windows' && 'windows-latest' || 'ubuntu-latest' }}
    strategy:
      matrix:
        os: [windows, linux]
        library_type: [shared, static]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Conan
      uses: conan-io/setup-conan@v1
      with:
        cache_packages: true

    - name: Build package and upload
      run: |
        conan create . --profile conan/profiles/${{ matrix.os }}_profile --build=missing -o moth_ui/*:Shared=${{ matrix.library_type == 'shared' && 'True' || 'False' }}
        conan remote add artifactory https://artifactory.matthewcotton.net/artifactory/api/conan/conan-local
        conan remote login artifactory ci -p ${{ secrets.ARTIFACTS_TOKEN }}
        conan upload moth_ui --confirm --remote artifactory
